# You have to define a function named isGreaterThan20 in which you have to pass two parameters to the function and the first parameter by default should be 20.


#Write a function named function_print_lines which takes 2 strings, and prints them in the following manner.

#If we give these 2 arguments - "My name is Rishabh." and "IWrite a function named function_print_lines which takes 2 strings, and prints them in the following manner.



# def function_print_lines(x):
#     print(x)
# function_print_lines("my name is rishib" )
# function_print_lines("I am the co-founder of NavGurukul")



# def greet(*names):
#     for name in names:
#         print("Welcome", name)


# greet("Rinki", "Vishal", "Kartik", "Bijender")






# def studentDetails(name,currentMilestone,mentorName):
#     print("Hello " , name, "your" , currentMilestone, "concept " , "is clear with the help of ", mentorName)


# studentDetails("Nilam","loop","teena")

