#add_numbers नामक एक फ़ंक्शन लिखें जो दो संख्याओं को argument के रूप में लेता है और फिर उनका योग प्रिंट करता है। arguments का नाम होना चाहिए number1 तथा number2 ।


# def add_numbers(num1,num2): 
#     c = num1+num2
#     print("sum two number",c)
      
# add_numbers(56,12)



# def add_number(num1,num2):
#     print("add ",num1+num2)
# add_number(12,56)   



# Write a function named add_numbers_list which takes 2 lists of two integers and then prints the sum of the integers with the same position.

# Use the add_numbers function given in Part 1 to count 2 integers that have the same position.

# If we give [50, 60, 10] and [10, 20, 13] to this function it will print this
# 60
# 80
# 23

# def add_number_list(x,y):
#     print("add sam index",x+y)
# add_number_list(50,10)   
# add_number_list(60,20)
# add_number_list(10,13) 





# def add():
#     a=int(input("enter the value of a"))
#     b=int(input("enter the value of b"))
#     c=a+b
#     return c
# result=add()    
# print("sum two number",result)
   

# def add():
#     a=int(input("enter the 1 no"))
#     b=int(input("enter the 2 no"))
#     c=a+b
#     return c
# x=add() 
# print("add two number",x)      

# a=[1,2,3,4,[1,2,3],[],[],5,6]
# a.remove([])
# a.remove([])
# print(a)

# a=int(input("enter the number"))
# i=0
# b=[]
# while i<a:
#     if a[i] not in b:
#         b.append(a)
#     else:

#     i=i+1
#     print(b)    


# def string(str1):
#     rstr1=""
#     index=len(str1)
#     while index>0:
#         rstr1+=str1[index-1]
#         index=index-1
#     return rstr1
# print(string("1234abcd"))
   
